--CREACION DE DOMINIOS

CREATE DOMAIN CLINICA.ID_PACIENTE AS CHAR(6) NOT NULL -- clinica.id_paciente es el nombre del dominio
	CHECK (VALUE ~ '^[P]{1}[-]{1}\d{4}$'); -- <- P-0001 4 digitos, ese seria el ID del domino
	
CREATE DOMAIN CLINICA.ID_MEESPECIALISTA AS CHAR(7) NOT NULL
	CHECK (VALUE ~ '^ME-\d{4}$'); 

CREATE DOMAIN CLINICA.ID_CITA AS CHAR(7) NOT NULL
	CHECK (VALUE ~ '^CM-\d{4}$'); 
	
-- CREACION DE TABLAS EMPEZANDO POR TABLAS RAIZ (LAS QUE NO DEPENDAN DE NADIE)
CREATE TABLE CLINICA.PACIENTE (
	PK_IDPACIENTE CLINICA.ID_PACIENTE, -- convencion para saber que esta columna es clave primaria de la tabla
	NOMBRE VARCHAR(20) NOT NULL,
	APELLIDO VARCHAR(20) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	FECHANACIMIENTO DATE NOT NULL,
	CIUDAD VARCHAR(20) NOT NULL,
	ESTADO VARCHAR(20) NOT NULL,
	TELEFONO CHAR(9) UNIQUE,
	PRIMARY KEY (PK_IDPACIENTE)
);
	
CREATE TABLE CLINICA.ESPECIALISTA(
	PK_IDESPECIALISTA CLINICA.ID_MEESPECIALISTA,
	NOMBRE VARCHAR(20) NOT NULL,
	APELLIDO VARCHAR(20) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	FECHANACIMIENTO DATE NOT NULL,
	ESPECIALIDAD VARCHAR(30) NOT NULL,
	PRIMARY KEY (PK_IDESPECIALISTA)
);

CREATE TABLE CLINICA.CITA (
	PK_IDCITA CLINICA.ID_CITA,
	FK_IDPACIENTE CLINICA.ID_PACIENTE,
	FECHA DATE NOT NULL,
	HORA TIME NOT NULL,
	PRIMARY KEY (PK_IDCITA),
	FOREIGN KEY (FK_IDPACIENTE) REFERENCES CLINICA.PACIENTE(PK_IDPACIENTE)
	-- fk_idPaciente debe existir en la tabla paciente
    -- No se puede crear una cita con un paciente que no existe
	ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE CLINICA.AGENDAR_CITA(
	FK_IDCITA CLINICA.ID_CITA,
	FK_IDESPECIALISTA CLINICA.ID_MEESPECIALISTA,
	CONSULTARIO VARCHAR(20) NOT NULL,
	FECHACITA DATE NOT NULL,
	HORACITA TIME NOT NULL,
	TURNO VARCHAR(10) NOT NULL,
	STATUS VARCHAR(10) NOT NULL,
	OBSERVACIONES VARCHAR(100) NOT NULL,
	-- CLAVE COMPUESTA POR EL ID CITA Y ID ESPECIALISTA
	PRIMARY KEY (FK_IDCITA, FK_IDESPECIALISTA),
	FOREIGN KEY (FK_IDCITA) REFERENCES CLINICA.CITA (PK_IDCITA)
	ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (FK_IDESPECIALISTA) REFERENCES CLINICA.ESPECIALISTA(PK_IDESPECIALISTA)
	ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE CLINICA.EXPEDIENTE (
	PK_IDPACIENTE CLINICA.ID_PACIENTE,
	TIPOSANGRE VARCHAR(10) NOT NULL,
	TIPOALERGIA VARCHAR(20) NOT NULL,
	PADECIMIENTOCRONICO VARCHAR(50),
	FECHACREACION TIMESTAMP NOT NULL,
	PRIMARY KEY (PK_IDPACIENTE),
	FOREIGN KEY (PK_IDPACIENTE) REFERENCES CLINICA.PACIENTE(PK_IDPACIENTE)
	ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE CLINICA.EXPEDIENTE_DIAGNOSTICO(
	-- serial es especial, es un valor entero que se autoincrementa 
	FOLIO SERIAL NOT NULL,
	FK_IDESPECIALISTA CLINICA.ID_MEESPECIALISTA,
	FK_IDPACIENTE CLINICA.ID_PACIENTE,
	EDAD CHAR(3) NOT NULL,
	PESO CHAR(3) NOT NULL,
	ALTURA CHAR(4) NOT NULL,
	IMC CHAR(5) NOT NULL,
	NIVELPESO CHAR(10) NOT NULL,
	PRESIONARTERIAL CHAR(8) NOT NULL,
	DIAGNOSTICO VARCHAR(150) NOT NULL,
	RECETARIO VARCHAR(150) NOT NULL,
	FECHACREACION TIMESTAMP NOT NULL,
	PRIMARY KEY (FOLIO),
	FOREIGN KEY (FK_IDESPECIALISTA) REFERENCES CLINICA.ESPECIALISTA(pk_idEspecialista)
	ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (FK_IDPACIENTE) REFERENCES CLINICA.PACIENTE (pk_idPaciente)
	ON UPDATE CASCADE ON DELETE CASCADE
);

-- AGREGAR UNA COLUMNA NUEVA
ALTER TABLE CLINICA.PACIENTE ADD COLUMN EJEMPLO VARCHAR(30);

-- BORRAR COLUMNA
ALTER TABLE CLINICA.PACIENTE DROP COLUMN EJEMPLO;

-- CAMBIAR TIPO DE DATO, TIENE QUE SER COMPATIBLE, ESTO NO LO ES
ALTER TABLE CLINICA.PACIENTE ALTER COLUMN EJEMPLO TYPE INT;

-- RENOMBRAR COLUMNA
ALTER TABLE CLINICA.PACIENTE RENAME COLUMN EJEMPLO TO NUEVO_NOMBRE;

-- RENOMBRAR UNA TABLA
ALTER TABLE CLINICA.PACIENTE RENAME TO PACIENTE_NUEVO;

ALTER TABLE CLINICA.PACIENTE_NUEVO RENAME TO PACIENTE;